### ISSUE TITLE
I want to join your team

### ISSUE THREAD

**Issue by kentaurse** [stocnet/rsiena#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TomSnijders** [comment]
Can you please identify yourself?

**Comment by kentaurse** [comment]
yeah sure.
I m Ethan Tan and I m from Singapore.
I am web full stack and blockchain developer.
Nice to  meet you

**Comment by TomSnijders** [comment]
Dear Ethan,
When searching by google I find several persons with name Ethan Tan in Singapore. 
Can you please give a more specific identification, and also indicate the reason why you would like to join the team and how you would like to contribute.

**Comment by kentaurse** [comment]
Dear @TomSnijders ,

Thank you for reaching out, and I'm glad to hear from you! I’m Ethan Tan, a Singapore-based full-stack developer specializing in advanced statistical applications, Web3, and full-stack web development. With a Bachelor's degree in Computer Science from the Singapore University of Technology and Design (SUTD) and over eight years of industry experience, I’ve built solutions for companies in fields ranging from FinTech to blockchain-based applications.

I’m interested in joining the Stocnet team because of its strong commitment to statistical analysis and social network modeling, an area that aligns closely with my professional background and personal interests. With my experience in languages like Python, R, and frameworks in web and network data visualization, I believe I could make significant contributions to the team, particularly by:

Enhancing the user interfaces and visualization capacities in manynet and migraph for network data representation.
Integrating scalable backend features and optimizing network data processing in goldfish for handling high-frequency relational event data.
Developing or refining tutorials and user guides to improve accessibility for new users.
Please let me know if I can provide additional details or examples of my previous work relevant to Stocnet’s objectives.

Best regards,
Ethan Tan

**Comment by nynkeniezink** [comment]
Hi Ethan,

Thanks for your interest in contributing to the Stocnet suite of R packages. It is great to hear you are interested in statistical modeling and social network analysis. As you may know, these packages were all developed and are maintained by people in academia. As such, no funding is available for you to contribute to these packages. I can imagine working for free on open-source software is not a viable business model for someone in industry. However, if you're still interested, feel free to help out with some of the [open issues](https://github.com/stocnet/rsiena/issues) in rsiena. 

Best regards,
Nynke Niezink
