### ISSUE TITLE
coDyadCovar and varDyadCovar do not accept sparse matrix with warn = TRUE

### ISSUE THREAD

**Issue by dvdkblk** [stocnet/rsiena#88]
**Describe the bug**
coDyadCovar and varDyadCovar both throw the error `Error in var(as.vector(val), na.rm = TRUE) : is.atomic(x) is not TRUE` when providing a sparse matrix (or a list thereof), unless you set `warn = FALSE`.

**To Reproduce**
For **coDyadCovar**:
``` 
library(RSiena)
library(tidyverse)

mat_sparse <- matrix(c(1:4), 2) %>% as('TsparseMatrix')   

# This will throw the error
covar <- coDyadCovar(mat_sparse ) 

# This will not
covar <- coDyadCovar(mat_sparse , warn = FALSE)

# Neither will this
mat <- matrix(c(1:4), 2) 
covar <- coDyadCovar(mat)
```

For **varDyadCovar**:
``` 
mat_sparse <- matrix(c(1:4), 2) %>% as('TsparseMatrix')
mat_list <- list(mat_sparse, mat_sparse)

# This will throw the error
covar <- varDyadCovar(mat_list) 

# This will not
covar <- varDyadCovar(mat_list, warn = FALSE) 
``` 

It seems to be linked to these lines, which you find in both functions: 
```
if ((!is.factor(val)) & warn) {
    if (var(as.vector(val), na.rm = TRUE)== 0) {
      warning("Note: all values are identical to ", mean(as.vector(val), 
                                                         na.rm = TRUE), ".")
    }
  }
``` 
Calling as.vector the list doesn't convert it to a vector so that it could be treated by var(). Crucially in `coDyadCovar `val gets converted to a list a few lines before:
``` 
if (!sparse) {
    if (!is.matrix(val)) {
      stop("val must be a matrix")
    }
    if (!(is.numeric(val) || is.factor(val))) {
      stop("val must be numeric or a factor")
    }
  }
  else {
    if (!inherits(val, "TsparseMatrix")) {
      stop("not a sparse triples matrix")
    }
    val <- list(val)
  }
```

**Setup**
 - OS: Win10
 - R Version 4.3.2
- Rsiena 1.4.1

**Comment by TomSnijders** [comment]
The code of coDyadCovar and varDyadCovar was changed in version 1.4.6 to correct this bug. The warning for constant values in the case of sparse data in coDyadCovar was changed and retained, in varDyadCovar it was dropped (for sparse data only).
